include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    always_use_package_imports: true
    prefer_single_quotes: true
    public_member_api_docs: false

analyzer:
  exclude:
    - build/**
